### ISSUE TITLE
Fatal Error with PDO Connection "SQLSTATE[HY000] [2002] Connection refused"

### ISSUE THREAD

**Issue by lyonsco** [susanBuck/e2-fall21#65] opened 2021-11-20 22:59 UTC
I followed the notes and class video in setting up the PDO connection to our database, but I am getting the following error message when I run in the browser (http://e2zipfoods.hesclyons.me/practice):

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/e2/zipfoods/app/Controllers/AppController.php:49 Stack trace: #0 /var/www/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(229): App\Controllers\AppController->practice() #1 /var/www/e2/zipfoods/public/index.php(15): E2\App->route() #2 {main} thrown in /var/www/e2/zipfoods/app/Controllers/AppController.php on line 49

Line 49 is this line from the try-catch statement:
```php
 throw new \PDOException($e->getMessage(), (int)$e->getCode());
```

What's strange is that it worked initially and I received the "Connection successful!" message from the dump, but then I took a break and came back to it and it is no longer working. I tried restarting VS code and reestablishing my connection to the server, but I am still receiving the issue. I also tried repasting in the code to make sure I don't have any errors. Is there something else I may be missing?

Thank you!
Courtney

**Comment by gotgits** [comment] 2021-11-21 15:39
Have you checked all of your closing brackets and semicolons before and after that statement, or stray text. My /practice dump arrays are all working. A fatal error often is caused by those issues.

**Comment by lyonsco** [comment] 2021-11-21 16:49
@gotgits, thank you for your reply! I checked everything and tried pasting everything again from the notes to be sure, and I am still getting the error. Here is my full code block for the practice function:

```php
    public function practice()
    {
        # Set up all the variables we need to make a connection
        $host = $this->app->env('DB_HOST');
        $database = $this->app->env('DB_NAME');
        $username = $this->app->env('DB_USERNAME');
        $password = $this->app->env('DB_PASSWORD');
        
        # DSN (Data Source Name) string
        # contains the information required to connect to the database
        $dsn = "mysql:host=$host;dbname=$database;charset=utf8mb4";
    
        # Driver-specific connection options
        $options = [
            \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
            \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
            \PDO::ATTR_EMULATE_PREPARES => false,
        ];
    
        try {
            # Create a PDO instance representing a connection to a database
            $pdo = new \PDO($dsn, $username, $password, $options);
        } catch (\PDOException $e) {
            throw new \PDOException($e->getMessage(), (int)$e->getCode());
        }
    
        dump('Connection successful!');
    }
}
```

**Comment by gotgits** [comment] 2021-11-21 17:08
> 
@lyonsco
http://e2zipfoods.metrognome.me/practice 
so that you can see it is working. Your code does look the same, and you are in the AppController of zipfoods? Could it be your routes.php

**Comment by lyonsco** [comment] 2021-11-21 17:10
@gotgits, I think I fixed it! I went back through the MySQL commands and I think the problem was that MySQL was no longer running, which wasn't allowing my application to connect to the database. I went through a few of the commands that we used to set up the database initially and then went back to browser and the connection is now successful.

Thank you for your help!

**Comment by susanBuck** [comment] 2021-11-21 23:27
@lyonsco Glad you sorted it! 

To test your theory, I purposefully stopped mysql (`sudo service mysql stop`) and ran my practice route and saw the same error you did (`SQLSTATE[HY000] [2002] Connection refused`). When I restarted MySQL (`sudo service mysql start`) it worked fine.

Not sure why MySQL would have stopped running for you, but if it happens again let me know and I can dig deeper.

**Closed as completed** 2021-11-28 22:56 UTC
